style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/ms
options:
  commits:
    filters:
      Type:
        - feat
        - impr
        - fix
        - doc
  commit_groups:
    title_maps:
      feat: Feature
      impr: Improvement
      fix: Bug destroyer
      doc: Documentation
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues: 
    prefix: 
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE